#!/bin/zsh

# cxhub macOS service setup script
# Compile cxhub, install it under /usr/local/opt, and run it as a LaunchAgent
# in the user's GUI domain so launchd supervises and restarts it.

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
CXHUB_USER="tony"
CXHUB_GROUP="staff"
USER_HOME="/Users/$CXHUB_USER"
PREFIX="/usr/local"
INSTALL_DIR="$PREFIX/opt/cxhub"
BINARY_PATH="$INSTALL_DIR/cxhub"
RUN_DIR="$PREFIX/var/cxhub"
DATA_DIR="$RUN_DIR/data"
# The live config lives in the user's config dir; the LaunchAgent reads it from
# there (see the wrapper below). Do not point the service at a shared root-owned
# copy unless you move the secrets too.
USER_CONFIG_DIR="$USER_HOME/.config/cxhub"
CONFIG_PATH="$USER_CONFIG_DIR/config.yaml"
ENV_PATH="$USER_CONFIG_DIR/env"
SERVICE_WRAPPER="$USER_CONFIG_DIR/cxhub-service.sh"
LAUNCHAGENTS_DIR="$USER_HOME/Library/LaunchAgents"
PLIST_PATH="$LAUNCHAGENTS_DIR/com.tony.cxhub.plist"
USER_LOG_DIR="$USER_HOME/Library/Logs/cxhub"
SERVICE_LOG="$USER_LOG_DIR/cxhub-service.log"
UID_NUM="$(id -u "$CXHUB_USER")"

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Check for sudo
echo "Checking for administrative privileges..."
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root or with sudo"
    echo "Try: sudo $0"
    exit 1
fi

# Check Go installation
if ! command -v go &> /dev/null; then
    log_error "Go is not installed or not in PATH"
    echo "Please install Go (https://golang.org/doc/install)"
    exit 1
fi

# Step 1: Create installation directories
log_info "Creating installation directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$RUN_DIR"
mkdir -p "$DATA_DIR"
mkdir -p "$LAUNCHAGENTS_DIR"
mkdir -p "$USER_LOG_DIR"
mkdir -p "$USER_CONFIG_DIR"

# Step 2: Compile the binary
log_info "Compiling cxhub..."
cd /Users/tony/build/cxhub

go build -o "$BINARY_PATH" ./cmd/cxhub

if [[ ! -f "$BINARY_PATH" ]]; then
    log_error "Failed to compile cxhub binary"
    exit 1
fi

log_info "Binary compiled successfully to $BINARY_PATH"

# Step 3: Set permissions
log_info "Setting permissions..."
chown -R $CXHUB_USER:$CXHUB_GROUP "$INSTALL_DIR"
chmod +x "$BINARY_PATH"
chmod 755 "$INSTALL_DIR"

# Step 4: Ensure the config exists and build the service env file.
# The config expands ${CLIPROXY_API_KEY} and ${OPENROUTER_API_KEY}; launchd does
# not read ~/.zshrc, so the wrapper sources a 0600 env file instead.
if [[ ! -f "$CONFIG_PATH" ]]; then
    log_warn "No config at $CONFIG_PATH"
    echo "  Copy one first, e.g.:"
    echo "  mkdir -p $USER_CONFIG_DIR"
    echo "  cp /Users/tony/build/cxhub/configs/example.yaml $CONFIG_PATH"
    echo "  then fill in the backends, profiles, and decision settings."
fi

if [[ ! -f "$ENV_PATH" ]]; then
    log_info "Creating service env file at $ENV_PATH (mode 0600)..."
    {
        echo "# Generated by setup-macOS.sh for the com.tony.cxhub LaunchAgent."
        if [[ -f "$USER_HOME/.config/cliproxyapi/api-key" ]]; then
            printf 'export CLIPROXY_API_KEY=%s\n' "$(cat "$USER_HOME/.config/cliproxyapi/api-key")"
        else
            echo "# export CLIPROXY_API_KEY=..."
        fi
        if [[ -n "${OPENROUTER_API_KEY:-}" ]]; then
            printf 'export OPENROUTER_API_KEY=%s\n' "$OPENROUTER_API_KEY"
        else
            echo "# export OPENROUTER_API_KEY=..."
        fi
    } > "$ENV_PATH"
fi
chmod 600 "$ENV_PATH"
chown $CXHUB_USER:$CXHUB_GROUP "$ENV_PATH"

log_info "Writing service wrapper to $SERVICE_WRAPPER"
cat > "$SERVICE_WRAPPER" <<EOF
#!/bin/sh
# LaunchAgent wrapper for cxhub. Absolute paths are used because launchd does
# not guarantee HOME; the env file is sourced and exported so the exec'd binary
# inherits the API keys the config expands.
set -eu
if [ -f "$ENV_PATH" ]; then
	set -a
	. "$ENV_PATH"
	set +a
fi
exec "$BINARY_PATH" start --config "$CONFIG_PATH" --pid-file "$USER_CONFIG_DIR/cxhub.pid"
EOF
chmod +x "$SERVICE_WRAPPER"
chown $CXHUB_USER:$CXHUB_GROUP "$SERVICE_WRAPPER"

# Step 5: Install LaunchAgent
log_info "Installing LaunchAgent..."
cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.tony.cxhub</string>
    <key>ProgramArguments</key>
    <array>
        <string>$SERVICE_WRAPPER</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>$SERVICE_LOG</string>
    <key>StandardErrorPath</key>
    <string>$SERVICE_LOG</string>
    <key>WorkingDirectory</key>
    <string>/Users/tony/build/cxhub</string>
</dict>
</plist>
EOF
# GUI-domain agents should be owned by the user, not root.
chown $CXHUB_USER:$CXHUB_GROUP "$PLIST_PATH"
chmod 644 "$PLIST_PATH"

# Step 6: (Re)load the service in the user's GUI domain
log_info "Loading LaunchAgent..."
launchctl bootout gui/$UID_NUM/com.tony.cxhub 2>/dev/null || true
if ! launchctl bootstrap gui/$UID_NUM "$PLIST_PATH"; then
    log_error "Failed to load LaunchAgent"
    echo "Try: launchctl bootstrap gui/$UID_NUM $PLIST_PATH"
    exit 1
fi

# Step 7: Show status
log_info "Setup complete!"
echo ""
echo "Service status:"
launchctl list | grep com.tony.cxhub || echo "Service not running (may be starting)..."
echo ""
echo "Configuration: $CONFIG_PATH"
echo "Service env:   $ENV_PATH (mode 0600)"
echo "Log:           $SERVICE_LOG"
echo ""
echo "Commands:"
echo "  Status: launchctl list com.tony.cxhub"
echo "  Stop:   launchctl bootout gui/$UID_NUM/com.tony.cxhub"
echo "  Start:  launchctl bootstrap gui/$UID_NUM $PLIST_PATH"
echo "  Restart:launchctl kickstart -k gui/$UID_NUM/com.tony.cxhub"
echo ""
echo "View logs: tail -f $SERVICE_LOG"

echo ""
log_info "Setup completed successfully!"